source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'rake', '10.1.0'
gem 'bootstrap-sass'
gem 'bcrypt-ruby'
gem 'faker'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'json'
gem 'curb'
gem 'hpricot'
gem 'nokogiri'
gem 'rss-nokogiri'
gem 'mechanize'
gem 'htmlentities'
gem 'aws-s3'
gem 'dropbox-sdk'
gem 'google-api-client'
gem 'google_drive'
gem 'httparty'
gem 'sendgrid'
gem 'smarter_csv'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
group :development, :test do
	gem 'mysql2', '0.3.10'
	gem 'rspec-rails'
	gem 'guard-rspec'
	gem 'guard-spork'
	gem 'spork'
end

group :development do
	gem 'annotate'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
	gem 'capybara'
	gem 'rb-inotify'
	gem 'libnotify'
	gem 'factory_girl_rails'
	gem 'database_cleaner'
end

group :production do
	gem 'pg'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
